project:
  type: website
  output-dir: docs

website:
  title: "SystemsBioVoit2025"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "About"
        href: about.qmd
      - section: "Basics"
        contents: basics

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



